export const base_url = "http://localhost:3003/api"
// export const base_url = "https://zwatch.tk"

export const loginPost          = "/auth/login"
export const signupPost         = "/auth/register"
export const googleLogin        = "/auth/google-login"
export const forgotPassword     = "/auth/forgot-password"
export const resetPassword      = "/auth/reset-password"
export const createPost         = "/post/create-post"
export const getPosts           = "/post/all-posts"
export const allUsers           = "/api/all-users"
export const deletePost         = "/post/delete-post"
export const addProfilePic      = "/add-profilepic"

export const verifyEmail        = "/api/verify-email"
export const updatePost         = "/api/update-post"
export const reportPost         = "/api/report-post"
export const editProfile        = "/api/edit-profile"
export const suggessions        = "/api/suggessions"
export const profileUser        = "/api/get-user"
export const addFollow          = "/api/add-friend"
export const removeFollow       = "/api/un-follow"
export const getFrieds          = "/api/getFriends"
export const unfollow           = "/api/un-follow"
export const unFriend           = "/api/remove-follower"
export const getMyPosts         = "/api/get-mypost"
export const notification       = "/api/all-notifications"
export const conversations      = "/api/chats"